exports.STATUS = {
    PENDING: "PENDING",
    CLOSED:'CLOSED',
    ELEVATED: "ELEVATED",
    UNRESOLVED: "UNRESOLVED"
}


exports.PRIORITY = {
    HIGH: "HIGH",
    LOW: "LOW",
    CRITICAL: "CRITICAL"
}
